-- NAMO Talk shared messaging schema
-- Supabase Dashboard > SQL Editor에서 한 번 실행하세요.

create table if not exists public.namo_talk_messages (
  id bigint generated by default as identity primary key,
  room_id text not null,
  sender_name text not null,
  sender_uid text,
  sender_dept text,
  message_type text not null default 'text',
  message_text text,
  file_name text,
  file_url text,
  created_at timestamptz not null default now()
);

create index if not exists namo_talk_messages_room_created_idx
  on public.namo_talk_messages (room_id, created_at);

alter table public.namo_talk_messages enable row level security;

drop policy if exists "namo talk read" on public.namo_talk_messages;
create policy "namo talk read"
  on public.namo_talk_messages
  for select
  using (true);

drop policy if exists "namo talk insert" on public.namo_talk_messages;
create policy "namo talk insert"
  on public.namo_talk_messages
  for insert
  with check (true);

-- 이미 publication에 포함된 경우 오류를 피하기 위한 처리
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.namo_talk_messages;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
