-- NAMO Talk shared messaging schema
-- Supabase Dashboard > SQL Editor에서 전체를 한 번 실행하세요.

create table if not exists public.namo_talk_messages (
  id bigint generated by default as identity primary key,
  room_id text not null,
  sender_name text not null,
  sender_uid text,
  sender_dept text,
  message_type text not null default 'text',
  message_text text,
  file_name text,
  file_url text,
  created_at timestamptz not null default now()
);

create index if not exists namo_talk_messages_room_created_idx
  on public.namo_talk_messages (room_id, created_at);

create table if not exists public.namo_talk_reads (
  room_id text not null,
  user_uid text not null,
  user_name text not null,
  last_read_at timestamptz not null default now(),
  primary key (room_id, user_uid)
);

create index if not exists namo_talk_reads_room_idx
  on public.namo_talk_reads (room_id, last_read_at);

alter table public.namo_talk_messages enable row level security;
alter table public.namo_talk_reads enable row level security;

drop policy if exists "namo talk read" on public.namo_talk_messages;
create policy "namo talk read" on public.namo_talk_messages for select using (true);

drop policy if exists "namo talk insert" on public.namo_talk_messages;
create policy "namo talk insert" on public.namo_talk_messages for insert with check (true);

drop policy if exists "namo talk delete own" on public.namo_talk_messages;
create policy "namo talk delete own" on public.namo_talk_messages
  for delete using (sender_uid is not null);

drop policy if exists "namo talk reads select" on public.namo_talk_reads;
create policy "namo talk reads select" on public.namo_talk_reads for select using (true);

drop policy if exists "namo talk reads insert" on public.namo_talk_reads;
create policy "namo talk reads insert" on public.namo_talk_reads for insert with check (true);

drop policy if exists "namo talk reads update" on public.namo_talk_reads;
create policy "namo talk reads update" on public.namo_talk_reads for update using (true) with check (true);

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.namo_talk_messages;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.namo_talk_reads;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;