'use strict';

// NAMO Chemical Attendance / Leave server module.
// Additive preload: installs attendance routes without replacing legacy QMES routes.
const express = require('express');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : false,
});

let schemaPromise = null;
const txt = v => (v ?? '').toString().trim();
const reply = (res, status, success, message, data = null) => res.status(status).json({ success, message, data });
const ok = (res, data = null, message = 'OK') => reply(res, 200, true, message, data);
const fail = (res, status, message) => reply(res, status, false, message, null);
const b64url = b => Buffer.from(b).toString('base64url');
const fromB64url = v => Buffer.from(String(v || ''), 'base64url');

function origin(req) {
  const o = txt(req.get('origin'));
  if (o) return o;
  const proto = txt(req.headers['x-forwarded-proto']).split(',')[0] || req.protocol || 'https';
  return `${proto}://${req.get('host')}`;
}
function rpId(req) { return txt(req.hostname || req.get('host')).replace(/:\d+$/, ''); }
function me(req) { return req.session?.user || null; }
function loginRequired(req,res,next){ if(!me(req)) return fail(res,401,'로그인이 필요합니다.'); next(); }
function adminRequired(req,res,next){ if(!me(req)||me(req).role!=='admin') return fail(res,403,'관리자 권한이 필요합니다.'); next(); }
function sessionUser(u){return{id:u.id,uid:u.uid||'',name:u.name,email:u.email,role:u.role,department:u.department||'',title:u.title||'',status:u.status,mustChangePassword:Boolean(u.must_change_password)}}

async function ensureSchema(){
  if(schemaPromise)return schemaPromise;
  schemaPromise=(async()=>{
    await pool.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto`);
    await pool.query(`
      CREATE TABLE IF NOT EXISTS attendance_profiles(
        user_id UUID PRIMARY KEY, annual_leave_days NUMERIC(6,1) NOT NULL DEFAULT 15.0,
        approver1_user_id UUID, approver2_user_id UUID, mobile_enabled BOOLEAN NOT NULL DEFAULT TRUE,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE TABLE IF NOT EXISTS attendance_logs(
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, work_date DATE NOT NULL,
        clock_in TIMESTAMPTZ, clock_out TIMESTAMPTZ, gps_in JSONB NOT NULL DEFAULT '{}'::jsonb,
        gps_out JSONB NOT NULL DEFAULT '{}'::jsonb, device_info TEXT DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        UNIQUE(user_id,work_date));
      CREATE INDEX IF NOT EXISTS attendance_logs_user_date_idx ON attendance_logs(user_id,work_date DESC);
      CREATE TABLE IF NOT EXISTS leave_requests(
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL, leave_type TEXT NOT NULL,
        start_date DATE NOT NULL, end_date DATE NOT NULL, days NUMERIC(6,1) NOT NULL, reason TEXT DEFAULT '',
        handover TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'PENDING_1', approver1_user_id UUID,
        approver2_user_id UUID, reject_reason TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE INDEX IF NOT EXISTS leave_requests_user_date_idx ON leave_requests(user_id,created_at DESC);
      CREATE INDEX IF NOT EXISTS leave_requests_approver_idx ON leave_requests(approver1_user_id,approver2_user_id,status);
      CREATE TABLE IF NOT EXISTS leave_approval_history(
        id BIGSERIAL PRIMARY KEY, leave_request_id UUID NOT NULL, actor_user_id UUID, actor_name TEXT DEFAULT '',
        action TEXT NOT NULL, reason TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE TABLE IF NOT EXISTS attendance_notifications(
        id BIGSERIAL PRIMARY KEY, user_id UUID NOT NULL, title TEXT NOT NULL, message TEXT DEFAULT '',
        target TEXT DEFAULT 'home', read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE INDEX IF NOT EXISTS attendance_notifications_user_idx ON attendance_notifications(user_id,created_at DESC);
      CREATE TABLE IF NOT EXISTS attendance_passkeys(
        id BIGSERIAL PRIMARY KEY, user_id UUID NOT NULL, credential_id TEXT UNIQUE NOT NULL,
        public_key_pem TEXT NOT NULL, algorithm INTEGER NOT NULL DEFAULT -7, sign_count BIGINT NOT NULL DEFAULT 0,
        transports JSONB NOT NULL DEFAULT '[]'::jsonb, label TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        last_used_at TIMESTAMPTZ);
      CREATE INDEX IF NOT EXISTS attendance_passkeys_user_idx ON attendance_passkeys(user_id);
      CREATE TABLE IF NOT EXISTS attendance_passkey_challenges(
        challenge TEXT PRIMARY KEY, user_id UUID NOT NULL, purpose TEXT NOT NULL,
        expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
      CREATE INDEX IF NOT EXISTS attendance_passkey_challenges_expire_idx ON attendance_passkey_challenges(expires_at);
    `);
    await pool.query(`DELETE FROM attendance_passkey_challenges WHERE expires_at<NOW()`);
  })().catch(e=>{schemaPromise=null;throw e});
  return schemaPromise;
}
async function ready(res){try{await ensureSchema();return true}catch(e){console.error('[Attendance] schema',e);fail(res,500,'근태관리 DB를 준비하지 못했습니다.');return false}}
async function userById(id){if(!id)return null;const r=await pool.query(`SELECT id,uid,name,email,department,title,role,status,must_change_password FROM users WHERE id=$1 LIMIT 1`,[id]);return r.rows[0]||null}
async function userByLogin(v){v=txt(v);if(!v)return null;const r=await pool.query(`SELECT id,uid,name,email,password_hash,department,title,role,status,must_change_password FROM users WHERE LOWER(email)=LOWER($1) OR LOWER(name)=LOWER($1) OR LOWER(COALESCE(uid,''))=LOWER($1) ORDER BY CASE WHEN LOWER(name)=LOWER($1) THEN 0 ELSE 1 END LIMIT 1`,[v]);return r.rows[0]||null}
async function defaultAdmin(exclude){const p=[];let c='';if(exclude){p.push(exclude);c='AND id<>$1'}const r=await pool.query(`SELECT id FROM users WHERE role='admin' AND status='APPROVED' ${c} ORDER BY created_at ASC LIMIT 1`,p);return r.rows[0]?.id||null}
async function profile(userId){let r=await pool.query(`SELECT * FROM attendance_profiles WHERE user_id=$1`,[userId]);if(r.rowCount)return r.rows[0];const a=await defaultAdmin(userId);r=await pool.query(`INSERT INTO attendance_profiles(user_id,annual_leave_days,approver2_user_id) VALUES($1,15.0,$2) ON CONFLICT(user_id) DO UPDATE SET user_id=EXCLUDED.user_id RETURNING *`,[userId,a]);return r.rows[0]}
async function label(id){const u=await userById(id);return u?{id:u.id,name:u.name,department:u.department||'',title:u.title||'',role:u.role}:null}
async function notify(userId,title,message,target='home'){if(userId)await pool.query(`INSERT INTO attendance_notifications(user_id,title,message,target) VALUES($1,$2,$3,$4)`,[userId,title,message,target])}
async function balance(userId){const p=await profile(userId);const r=await pool.query(`SELECT COALESCE(SUM(days),0)::numeric used FROM leave_requests WHERE user_id=$1 AND status='APPROVED' AND EXTRACT(YEAR FROM start_date)=EXTRACT(YEAR FROM (NOW() AT TIME ZONE 'Asia/Seoul'))`,[userId]);const granted=Number(p.annual_leave_days||15),used=Number(r.rows[0]?.used||0);return{granted,used,remaining:Math.max(0,granted-used)}}
const logDto=r=>({id:r.id,workDate:r.work_date,clockIn:r.clock_in,clockOut:r.clock_out,gpsIn:r.gps_in||{},gpsOut:r.gps_out||{},deviceInfo:r.device_info||''});

function install(app){
  if(app.__namoAttendanceInstalled)return;app.__namoAttendanceInstalled=true;
  ensureSchema().catch(e=>console.error('[Attendance] init',e));
  app.get('/attendance',(_req,res)=>res.redirect('/attendance.html'));

  app.get('/api/attendance/me',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const u=await userById(me(req).id);if(!u)return fail(res,404,'회원정보를 찾을 수 없습니다.');const p=await profile(u.id),b=await balance(u.id),n=Number((await pool.query(`SELECT COUNT(*)::int n FROM attendance_passkeys WHERE user_id=$1`,[u.id])).rows[0]?.n||0);ok(res,{user:sessionUser(u),balance:b,passkeyCount:n,profile:{annualLeaveDays:Number(p.annual_leave_days||15),mobileEnabled:Boolean(p.mobile_enabled),approver1:await label(p.approver1_user_id),approver2:await label(p.approver2_user_id)}})}catch(e){console.error('[Attendance] me',e);fail(res,500,'사용자 정보를 불러오지 못했습니다.')}});
  app.get('/api/attendance/today',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const r=await pool.query(`SELECT * FROM attendance_logs WHERE user_id=$1 AND work_date=(NOW() AT TIME ZONE 'Asia/Seoul')::date LIMIT 1`,[me(req).id]);ok(res,r.rowCount?logDto(r.rows[0]):null)}catch(e){fail(res,500,'오늘 근태를 불러오지 못했습니다.')}});
  app.post('/api/attendance/clock-in',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const gps=req.body?.gps&&typeof req.body.gps==='object'?req.body.gps:{},device=txt(req.body?.device).slice(0,500);const r=await pool.query(`INSERT INTO attendance_logs(user_id,work_date,clock_in,gps_in,device_info) VALUES($1,(NOW() AT TIME ZONE 'Asia/Seoul')::date,NOW(),$2::jsonb,$3) ON CONFLICT(user_id,work_date) DO UPDATE SET clock_in=COALESCE(attendance_logs.clock_in,EXCLUDED.clock_in),gps_in=CASE WHEN attendance_logs.clock_in IS NULL THEN EXCLUDED.gps_in ELSE attendance_logs.gps_in END,device_info=CASE WHEN attendance_logs.clock_in IS NULL THEN EXCLUDED.device_info ELSE attendance_logs.device_info END,updated_at=NOW() RETURNING *`,[me(req).id,JSON.stringify(gps),device]);ok(res,logDto(r.rows[0]),'출근 처리되었습니다.')}catch(e){console.error('[Attendance] in',e);fail(res,500,'출근 처리에 실패했습니다.')}});
  app.post('/api/attendance/clock-out',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const gps=req.body?.gps&&typeof req.body.gps==='object'?req.body.gps:{};const r=await pool.query(`UPDATE attendance_logs SET clock_out=COALESCE(clock_out,NOW()),gps_out=CASE WHEN clock_out IS NULL THEN $2::jsonb ELSE gps_out END,updated_at=NOW() WHERE user_id=$1 AND work_date=(NOW() AT TIME ZONE 'Asia/Seoul')::date AND clock_in IS NOT NULL RETURNING *`,[me(req).id,JSON.stringify(gps)]);if(!r.rowCount)return fail(res,400,'먼저 출근 처리를 해주세요.');ok(res,logDto(r.rows[0]),'퇴근 처리되었습니다.')}catch(e){fail(res,500,'퇴근 처리에 실패했습니다.')}});
  app.get('/api/attendance/logs',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const m=/^\d{4}-\d{2}$/.test(txt(req.query.month))?txt(req.query.month):null;const r=m?await pool.query(`SELECT * FROM attendance_logs WHERE user_id=$1 AND TO_CHAR(work_date,'YYYY-MM')=$2 ORDER BY work_date DESC`,[me(req).id,m]):await pool.query(`SELECT * FROM attendance_logs WHERE user_id=$1 ORDER BY work_date DESC LIMIT 100`,[me(req).id]);ok(res,r.rows.map(logDto))}catch(e){fail(res,500,'근태기록을 불러오지 못했습니다.')}});

  app.get('/api/attendance/leave',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const r=await pool.query(`SELECT l.*,a1.name approver1_name,a2.name approver2_name FROM leave_requests l LEFT JOIN users a1 ON a1.id=l.approver1_user_id LEFT JOIN users a2 ON a2.id=l.approver2_user_id WHERE l.user_id=$1 ORDER BY l.created_at DESC LIMIT 200`,[me(req).id]);ok(res,{requests:r.rows,balance:await balance(me(req).id)})}catch(e){fail(res,500,'연차 내역을 불러오지 못했습니다.')}});
  app.post('/api/attendance/leave',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const u=me(req),type=txt(req.body?.leaveType||'annual'),start=txt(req.body?.startDate),end=txt(req.body?.endDate||start),days=Number(req.body?.days),reason=txt(req.body?.reason).slice(0,1000),handover=txt(req.body?.handover).slice(0,2000);if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))return fail(res,400,'연차 날짜를 확인해주세요.');if(!Number.isFinite(days)||days<=0||days>31)return fail(res,400,'연차 일수를 확인해주세요.');const b=await balance(u.id);if(days>b.remaining)return fail(res,400,`잔여 연차가 부족합니다. 현재 ${b.remaining}일입니다.`);const p=await profile(u.id);let a1=p.approver1_user_id||null,a2=p.approver2_user_id||null;if(!a1&&!a2)a2=await defaultAdmin(u.id);if(!a1&&!a2)return fail(res,400,'승인권자가 설정되지 않았습니다.');const status=a1?'PENDING_1':'PENDING_2';const r=await pool.query(`INSERT INTO leave_requests(user_id,leave_type,start_date,end_date,days,reason,handover,status,approver1_user_id,approver2_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[u.id,type,start,end,days,reason,handover,status,a1,a2]);await pool.query(`INSERT INTO leave_approval_history(leave_request_id,actor_user_id,actor_name,action) VALUES($1,$2,$3,'SUBMIT')`,[r.rows[0].id,u.id,u.name]);await notify(status==='PENDING_1'?a1:a2,'연차 승인 요청',`${u.name} ${u.title||''} · ${start} · ${days}일`,'approval');ok(res,r.rows[0],'연차 신청 완료 · 승인권자에게 알림을 보냈습니다.')}catch(e){console.error('[Attendance] leave',e);fail(res,500,'연차 신청에 실패했습니다.')}});
  app.get('/api/attendance/approvals',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const r=await pool.query(`SELECT l.*,u.name employee_name,u.department employee_department,u.title employee_title,a1.name approver1_name,a2.name approver2_name FROM leave_requests l JOIN users u ON u.id=l.user_id LEFT JOIN users a1 ON a1.id=l.approver1_user_id LEFT JOIN users a2 ON a2.id=l.approver2_user_id WHERE (l.status='PENDING_1' AND l.approver1_user_id=$1) OR (l.status='PENDING_2' AND l.approver2_user_id=$1) ORDER BY l.created_at ASC`,[me(req).id]);ok(res,r.rows)}catch(e){fail(res,500,'승인함을 불러오지 못했습니다.')}});
  app.post('/api/attendance/leave/:id/approve',loginRequired,async(req,res)=>{if(!await ready(res))return;const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`SELECT l.*,u.name employee_name FROM leave_requests l JOIN users u ON u.id=l.user_id WHERE l.id=$1 FOR UPDATE`,[req.params.id]);if(!r.rowCount){await c.query('ROLLBACK');return fail(res,404,'신청내역을 찾을 수 없습니다.')}const l=r.rows[0],u=me(req);let next,target=null,action;if(l.status==='PENDING_1'&&String(l.approver1_user_id)===String(u.id)){if(l.approver2_user_id){next='PENDING_2';target=l.approver2_user_id;action='APPROVE_1'}else{next='APPROVED';action='APPROVE_FINAL'}}else if(l.status==='PENDING_2'&&String(l.approver2_user_id)===String(u.id)){next='APPROVED';action='APPROVE_FINAL'}else{await c.query('ROLLBACK');return fail(res,403,'현재 승인권자가 아닙니다.')}await c.query(`UPDATE leave_requests SET status=$2,updated_at=NOW() WHERE id=$1`,[l.id,next]);await c.query(`INSERT INTO leave_approval_history(leave_request_id,actor_user_id,actor_name,action) VALUES($1,$2,$3,$4)`,[l.id,u.id,u.name,action]);await c.query('COMMIT');if(target)await notify(target,'연차 최종승인 요청',`${l.employee_name} · ${l.start_date} · ${Number(l.days)}일`,'approval');else await notify(l.user_id,'연차 최종 승인 완료',`${l.start_date} 연차 ${Number(l.days)}일이 최종 승인되었습니다.`,'leave');ok(res,{status:next},target?'1차 승인 완료 · 최종 승인자에게 전달했습니다.':'최종 승인되었습니다.')}catch(e){await c.query('ROLLBACK').catch(()=>{});console.error('[Attendance] approve',e);fail(res,500,'승인 처리에 실패했습니다.')}finally{c.release()}});
  app.post('/api/attendance/leave/:id/reject',loginRequired,async(req,res)=>{if(!await ready(res))return;const reason=txt(req.body?.reason).slice(0,1000);if(!reason)return fail(res,400,'반려 사유를 입력해주세요.');const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`SELECT l.*,u.name employee_name FROM leave_requests l JOIN users u ON u.id=l.user_id WHERE l.id=$1 FOR UPDATE`,[req.params.id]);if(!r.rowCount){await c.query('ROLLBACK');return fail(res,404,'신청내역을 찾을 수 없습니다.')}const l=r.rows[0],u=me(req),allowed=(l.status==='PENDING_1'&&String(l.approver1_user_id)===String(u.id))||(l.status==='PENDING_2'&&String(l.approver2_user_id)===String(u.id));if(!allowed){await c.query('ROLLBACK');return fail(res,403,'현재 승인권자가 아닙니다.')}await c.query(`UPDATE leave_requests SET status='REJECTED',reject_reason=$2,updated_at=NOW() WHERE id=$1`,[l.id,reason]);await c.query(`INSERT INTO leave_approval_history(leave_request_id,actor_user_id,actor_name,action,reason) VALUES($1,$2,$3,'REJECT',$4)`,[l.id,u.id,u.name,reason]);await c.query('COMMIT');await notify(l.user_id,'연차 신청 반려',`${l.start_date} 신청이 반려되었습니다. 사유: ${reason}`,'leave');ok(res,{status:'REJECTED'},'반려 처리되었습니다.')}catch(e){await c.query('ROLLBACK').catch(()=>{});fail(res,500,'반려 처리에 실패했습니다.')}finally{c.release()}});

  app.get('/api/attendance/notifications',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const r=await pool.query(`SELECT id,title,message,target,read_at,created_at FROM attendance_notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[me(req).id]);ok(res,r.rows)}catch(e){fail(res,500,'알림을 불러오지 못했습니다.')}});
  app.post('/api/attendance/notifications/read-all',loginRequired,async(req,res)=>{if(!await ready(res))return;try{await pool.query(`UPDATE attendance_notifications SET read_at=COALESCE(read_at,NOW()) WHERE user_id=$1`,[me(req).id]);ok(res,null,'모두 읽음 처리했습니다.')}catch(e){fail(res,500,'알림 처리에 실패했습니다.')}});

  app.get('/api/attendance/admin/members',adminRequired,async(req,res)=>{if(!await ready(res))return;try{const r=await pool.query(`SELECT u.id,u.uid,u.name,u.email,u.department,u.title,u.role,u.status,u.created_at,COALESCE(p.annual_leave_days,15.0) annual_leave_days,p.approver1_user_id,p.approver2_user_id,a1.name approver1_name,a2.name approver2_name FROM users u LEFT JOIN attendance_profiles p ON p.user_id=u.id LEFT JOIN users a1 ON a1.id=p.approver1_user_id LEFT JOIN users a2 ON a2.id=p.approver2_user_id ORDER BY u.name ASC`);ok(res,r.rows)}catch(e){fail(res,500,'회원목록을 불러오지 못했습니다.')}});
  app.post('/api/attendance/admin/members',adminRequired,async(req,res)=>{if(!await ready(res))return;const name=txt(req.body?.name),department=txt(req.body?.department),title=txt(req.body?.title),role=txt(req.body?.role||'user')==='admin'?'admin':'user',annual=Number(req.body?.annualLeaveDays??15),a1=txt(req.body?.approver1UserId)||null,a2=txt(req.body?.approver2UserId)||null;if(!name)return fail(res,400,'이름을 입력해주세요.');const c=await pool.connect();try{await c.query('BEGIN');if((await c.query(`SELECT id FROM users WHERE LOWER(name)=LOWER($1) LIMIT 1`,[name])).rowCount){await c.query('ROLLBACK');return fail(res,409,'같은 이름의 회원이 이미 있습니다.')}const hash=await bcrypt.hash('1234',12),random=crypto.randomUUID().replace(/-/g,'').slice(0,12),uid=`NAMO-${random.toUpperCase()}`,email=`attendance-${random}@namochemical.local`;const u=await c.query(`INSERT INTO users(name,email,password_hash,department,title,role,status,uid,must_change_password) VALUES($1,$2,$3,$4,$5,$6,'APPROVED',$7,TRUE) RETURNING id,uid,name,email,department,title,role,status`,[name,email,hash,department,title,role,uid]);await c.query(`INSERT INTO attendance_profiles(user_id,annual_leave_days,approver1_user_id,approver2_user_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET annual_leave_days=EXCLUDED.annual_leave_days,approver1_user_id=EXCLUDED.approver1_user_id,approver2_user_id=EXCLUDED.approver2_user_id,updated_at=NOW()`,[u.rows[0].id,Number.isFinite(annual)?annual:15,a1,a2]);await c.query('COMMIT');ok(res,u.rows[0],'회원등록 완료 · 로그인 ID는 이름, 초기 비밀번호는 1234입니다.')}catch(e){await c.query('ROLLBACK').catch(()=>{});console.error('[Attendance] member create',e);fail(res,500,'회원등록에 실패했습니다.')}finally{c.release()}});
  app.put('/api/attendance/admin/members/:id',adminRequired,async(req,res)=>{if(!await ready(res))return;const name=txt(req.body?.name),department=txt(req.body?.department),title=txt(req.body?.title),role=txt(req.body?.role||'user')==='admin'?'admin':'user',status=txt(req.body?.status||'APPROVED'),annual=Number(req.body?.annualLeaveDays??15),a1=txt(req.body?.approver1UserId)||null,a2=txt(req.body?.approver2UserId)||null;if(!name)return fail(res,400,'이름을 입력해주세요.');const c=await pool.connect();try{await c.query('BEGIN');if((await c.query(`SELECT id FROM users WHERE LOWER(name)=LOWER($1) AND id<>$2 LIMIT 1`,[name,req.params.id])).rowCount){await c.query('ROLLBACK');return fail(res,409,'같은 이름의 회원이 이미 있습니다.')}const u=await c.query(`UPDATE users SET name=$2,department=$3,title=$4,role=$5,status=$6 WHERE id=$1 RETURNING id,uid,name,email,department,title,role,status`,[req.params.id,name,department,title,role,status]);if(!u.rowCount){await c.query('ROLLBACK');return fail(res,404,'회원을 찾을 수 없습니다.')}await c.query(`INSERT INTO attendance_profiles(user_id,annual_leave_days,approver1_user_id,approver2_user_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET annual_leave_days=EXCLUDED.annual_leave_days,approver1_user_id=EXCLUDED.approver1_user_id,approver2_user_id=EXCLUDED.approver2_user_id,updated_at=NOW()`,[req.params.id,Number.isFinite(annual)?annual:15,a1,a2]);await c.query('COMMIT');ok(res,u.rows[0],'회원정보를 수정했습니다.')}catch(e){await c.query('ROLLBACK').catch(()=>{});fail(res,500,'회원수정에 실패했습니다.')}finally{c.release()}});
  app.post('/api/attendance/admin/members/:id/reset-password',adminRequired,async(req,res)=>{if(!await ready(res))return;try{const hash=await bcrypt.hash('1234',12),r=await pool.query(`UPDATE users SET password_hash=$2,must_change_password=TRUE WHERE id=$1 RETURNING id,name`,[req.params.id,hash]);if(!r.rowCount)return fail(res,404,'회원을 찾을 수 없습니다.');ok(res,r.rows[0],'비밀번호를 1234로 초기화했습니다.')}catch(e){fail(res,500,'비밀번호 초기화에 실패했습니다.')}});

  app.post('/api/attendance/passkey/register/options',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const u=await userById(me(req).id),challenge=b64url(crypto.randomBytes(32));await pool.query(`DELETE FROM attendance_passkey_challenges WHERE user_id=$1 AND purpose='register'`,[u.id]);await pool.query(`INSERT INTO attendance_passkey_challenges(challenge,user_id,purpose,expires_at) VALUES($1,$2,'register',NOW()+INTERVAL '5 minutes')`,[challenge,u.id]);const ex=await pool.query(`SELECT credential_id FROM attendance_passkeys WHERE user_id=$1`,[u.id]);ok(res,{challenge,rp:{id:rpId(req),name:'NAMO Chemical'},user:{id:b64url(Buffer.from(String(u.id))),name:u.name,displayName:`${u.name} ${u.title||''}`.trim()},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],timeout:60000,authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},attestation:'none',excludeCredentials:ex.rows.map(x=>({type:'public-key',id:x.credential_id}))})}catch(e){console.error('[Attendance] passkey options',e);fail(res,500,'생체인증 등록 준비에 실패했습니다.')}});
  app.post('/api/attendance/passkey/register/verify',loginRequired,async(req,res)=>{if(!await ready(res))return;try{const u=me(req),challenge=txt(req.body?.challenge),credentialId=txt(req.body?.credentialId),publicKey=txt(req.body?.publicKey),algorithm=Number(req.body?.algorithm||-7),clientDataRaw=txt(req.body?.clientDataJSON);if(!challenge||!credentialId||!publicKey||!clientDataRaw)return fail(res,400,'생체인증 등록 데이터가 부족합니다.');if(!(await pool.query(`SELECT 1 FROM attendance_passkey_challenges WHERE challenge=$1 AND user_id=$2 AND purpose='register' AND expires_at>NOW()`,[challenge,u.id])).rowCount)return fail(res,400,'생체인증 등록 요청이 만료되었습니다.');const cd=JSON.parse(fromB64url(clientDataRaw).toString('utf8'));if(cd.type!=='webauthn.create'||cd.challenge!==challenge||cd.origin!==origin(req))return fail(res,400,'생체인증 등록 검증에 실패했습니다.');const key=crypto.createPublicKey({key:fromB64url(publicKey),format:'der',type:'spki'}).export({format:'pem',type:'spki'}).toString(),transports=Array.isArray(req.body?.transports)?req.body.transports:[];await pool.query(`INSERT INTO attendance_passkeys(user_id,credential_id,public_key_pem,algorithm,transports,label) VALUES($1,$2,$3,$4,$5::jsonb,$6) ON CONFLICT(credential_id) DO UPDATE SET user_id=EXCLUDED.user_id,public_key_pem=EXCLUDED.public_key_pem,algorithm=EXCLUDED.algorithm,transports=EXCLUDED.transports`,[u.id,credentialId,key,algorithm,JSON.stringify(transports),txt(req.body?.label||'휴대폰 생체인증')]);await pool.query(`DELETE FROM attendance_passkey_challenges WHERE challenge=$1`,[challenge]);ok(res,null,'생체인증 등록이 완료되었습니다.')}catch(e){console.error('[Attendance] passkey register',e);fail(res,500,'생체인증 등록에 실패했습니다.')}});
  app.post('/api/attendance/passkey/login/options',async(req,res)=>{if(!await ready(res))return;try{const u=await userByLogin(req.body?.loginId);if(!u||u.status!=='APPROVED')return fail(res,404,'등록된 생체인증 계정을 찾을 수 없습니다.');const cs=await pool.query(`SELECT credential_id,transports FROM attendance_passkeys WHERE user_id=$1`,[u.id]);if(!cs.rowCount)return fail(res,404,'먼저 일반 로그인 후 내 정보에서 생체인증을 등록해주세요.');const challenge=b64url(crypto.randomBytes(32));await pool.query(`DELETE FROM attendance_passkey_challenges WHERE user_id=$1 AND purpose='login'`,[u.id]);await pool.query(`INSERT INTO attendance_passkey_challenges(challenge,user_id,purpose,expires_at) VALUES($1,$2,'login',NOW()+INTERVAL '5 minutes')`,[challenge,u.id]);ok(res,{challenge,rpId:rpId(req),timeout:60000,userVerification:'required',allowCredentials:cs.rows.map(c=>({type:'public-key',id:c.credential_id,transports:Array.isArray(c.transports)?c.transports:[]}))})}catch(e){fail(res,500,'생체인증 로그인 준비에 실패했습니다.')}});
  app.post('/api/attendance/passkey/login/verify',async(req,res)=>{if(!await ready(res))return;try{const challenge=txt(req.body?.challenge),credentialId=txt(req.body?.credentialId),clientDataRaw=txt(req.body?.clientDataJSON),authDataRaw=txt(req.body?.authenticatorData),sigRaw=txt(req.body?.signature);if(!challenge||!credentialId||!clientDataRaw||!authDataRaw||!sigRaw)return fail(res,400,'생체인증 로그인 데이터가 부족합니다.');const ch=await pool.query(`SELECT * FROM attendance_passkey_challenges WHERE challenge=$1 AND purpose='login' AND expires_at>NOW()`,[challenge]);if(!ch.rowCount)return fail(res,400,'생체인증 로그인 요청이 만료되었습니다.');const cr=await pool.query(`SELECT * FROM attendance_passkeys WHERE credential_id=$1 AND user_id=$2`,[credentialId,ch.rows[0].user_id]);if(!cr.rowCount)return fail(res,403,'등록되지 않은 생체인증입니다.');const clientBytes=fromB64url(clientDataRaw),cd=JSON.parse(clientBytes.toString('utf8'));if(cd.type!=='webauthn.get'||cd.challenge!==challenge||cd.origin!==origin(req))return fail(res,400,'생체인증 요청 검증에 실패했습니다.');const auth=fromB64url(authDataRaw);if(auth.length<37)return fail(res,400,'생체인증 데이터 형식이 올바르지 않습니다.');const rpHash=crypto.createHash('sha256').update(rpId(req)).digest();if(!crypto.timingSafeEqual(auth.subarray(0,32),rpHash))return fail(res,400,'생체인증 도메인 검증에 실패했습니다.');const flags=auth[32];if(!(flags&1)||!(flags&4))return fail(res,403,'휴대폰 사용자 인증이 완료되지 않았습니다.');const signed=Buffer.concat([auth,crypto.createHash('sha256').update(clientBytes).digest()]);if(!crypto.verify('sha256',signed,cr.rows[0].public_key_pem,fromB64url(sigRaw)))return fail(res,403,'생체인증 서명을 확인할 수 없습니다.');const u=await userById(ch.rows[0].user_id);if(!u||u.status!=='APPROVED')return fail(res,403,'사용할 수 없는 계정입니다.');await pool.query(`UPDATE attendance_passkeys SET sign_count=GREATEST(sign_count,$2),last_used_at=NOW() WHERE id=$1`,[cr.rows[0].id,auth.readUInt32BE(33)]);await pool.query(`DELETE FROM attendance_passkey_challenges WHERE challenge=$1`,[challenge]);await new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));req.session.user=sessionUser(u);await new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));ok(res,{user:req.session.user},'생체인증 로그인 완료')}catch(e){console.error('[Attendance] passkey login',e);fail(res,500,'생체인증 로그인에 실패했습니다.')}});
  app.delete('/api/attendance/passkey',loginRequired,async(req,res)=>{if(!await ready(res))return;try{await pool.query(`DELETE FROM attendance_passkeys WHERE user_id=$1`,[me(req).id]);ok(res,null,'생체인증 등록을 해제했습니다.')}catch(e){fail(res,500,'생체인증 해제에 실패했습니다.')}});
}

const oldGet=express.application.get,oldPost=express.application.post,oldPut=express.application.put,oldDelete=express.application.delete;
function before(app,path){if(typeof path==='string'&&(path.startsWith('/api/')||path==='/attendance')&&!app.__namoAttendanceInstalled)install(app)}
express.application.get=function(p,...h){before(this,p);return oldGet.call(this,p,...h)};
express.application.post=function(p,...h){before(this,p);return oldPost.call(this,p,...h)};
express.application.put=function(p,...h){before(this,p);return oldPut.call(this,p,...h)};
express.application.delete=function(p,...h){before(this,p);return oldDelete.call(this,p,...h)};
module.exports={installAttendanceRoutes:install};
