/* QMES module: 거래처 현황 */
function PartnersTab() {
  const defaultCustomers=[{code:"CUS001",name:"현대자동차",status:"거래중"},{code:"CUS002",name:"삼성SDI",status:"거래중"},{code:"CUS003",name:"LG에너지솔루션",status:"거래중"},{code:"CUS004",name:"SK온",status:"거래중"}];
  const defaultSuppliers=[{code:"SUP001",company:"코오롱",material:"PAI",lot:"PAI#27-2(2)",status:"거래중"},{code:"SUP002",company:"푸양광명화학",material:"NMP",lot:"20251031063",status:"거래중"},{code:"SUP003",company:"모리로쿠케미칼즈",material:"NMP",lot:"2026011101",status:"거래중"},{code:"SUP004",company:"강신산업",material:"Boehmite",lot:"006-8-25",status:"거래중"},{code:"SUP005",company:"LG화학",material:"SBR",lot:"C3026B26A(1)",status:"거래중"},{code:"SUP006",company:"SOLVAY",material:"PVDF",lot:"CSE23202TA",status:"거래중"},{code:"SUP007",company:"금호석유화학",material:"SBS",lot:"W251016",status:"거래중"},{code:"SUP008",company:"유니소재",material:"BYK180 (분산제)",lot:"2708935",status:"거래중"}];
  const normalizeMaterial=name=>{const v=String(name||"").toUpperCase().replace(/\s+/g,"");if(v.includes("BYK180")||v.includes("BYK-180")||v.includes("분산제"))return"BYK180";if(v.includes("AOH30")||v.includes("BOEHMITE"))return"BOEHMITE";for(const x of["PVDF","PAI","NMP","SBR","SBS"])if(v.includes(x))return x;return v;};
  const standardMaterialName=name=>normalizeMaterial(name)==="BYK180"?"BYK180 (분산제)":String(name||"").trim();
  const[activeType,setActiveType]=React.useState("customer"),[searchText,setSearchText]=React.useState(""),[saveMessage,setSaveMessage]=React.useState("");
  const[customers]=React.useState(()=>{const s=Array.isArray(DB?.partnerCustomers)?DB.partnerCustomers:[];return s.length?s:defaultCustomers;});
  const[suppliers,setSuppliers]=React.useState(()=>{const s=Array.isArray(DB?.partnerSuppliers)?DB.partnerSuppliers:[];if(!s.length)return defaultSuppliers;const m=defaultSuppliers.map(i=>{const o=s.find(r=>r.code===i.code);return o?{...i,...o,material:standardMaterialName(o.material||i.material)}:i;});s.filter(r=>!m.some(i=>i.code===r.code)).forEach(r=>m.push({...r,material:standardMaterialName(r.material)}));return m;});
  const persist=(nc=customers,ns=suppliers)=>{DB.partnerCustomers=nc.map(r=>({...r}));DB.partnerSuppliers=ns.map(r=>({...r,material:standardMaterialName(r.material)}));DB.rawMaterialLots=ns.reduce((a,r)=>{a[`${normalizeMaterial(r.material)}|${r.company}`]={material:standardMaterialName(r.material),supplier:r.company,lot:String(r.lot||"").trim(),status:r.status,updatedAt:new Date().toISOString(),by:window.__QMES_USER__||"-"};return a;},{});dbSave();};
  const syncLotsToWorkOrders=rows=>{let n=0;const latest={};rows.forEach(r=>{const k=normalizeMaterial(r.material);if(String(r.lot||"").trim()&&!latest[k])latest[k]=r;});Object.entries(DB?.woDocs||{}).forEach(([wo,doc])=>{if(!Array.isArray(doc.inputs))return;let changed=false;const inputs=doc.inputs.map(input=>{const master=latest[normalizeMaterial(input.name)],cur=String(input.materialLot||input.lot||"").trim();if(!master||cur)return input;changed=true;n++;return{...input,lot:master.lot,materialLot:master.lot,supplier:master.company,lotSource:"거래처 현황"};});if(changed)DB.woDocs[wo]={...doc,inputs};});return n;};
  const switchType=t=>{setActiveType(t);setSearchText("");setSaveMessage("");};
  const saveSupplierLots=()=>{try{persist();const n=syncLotsToWorkOrders(suppliers);dbSave();setSaveMessage(`원료 LOT 저장 완료 · 빈 작업지시서 원료 LOT ${n}건 자동 반영`);}catch(e){console.warn(e);setSaveMessage("저장 중 오류가 발생했습니다.");}};
  const updateSupplierLot=(code,lot)=>setSuppliers(p=>p.map(r=>r.code===code?{...r,lot}:r));
  const k=searchText.trim().toLowerCase();
  const filteredCustomers=customers.filter(i=>[i.code,i.name,i.status].some(v=>String(v||"").toLowerCase().includes(k)));
  const filteredSuppliers=suppliers.filter(i=>[i.code,i.company,i.material,i.lot,i.status].some(v=>String(v||"").toLowerCase().includes(k))).sort((a,b)=>a.company.localeCompare(b.company,"ko-KR",{numeric:true,sensitivity:"base"}));
  const inputClass="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-black outline-none placeholder:text-slate-500 focus:border-cyan-500";
  const btnEdit="rounded-md border border-slate-400 bg-white px-3 py-1.5 text-xs font-semibold text-black hover:bg-slate-100";
  const activeTab="border-cyan-500 bg-cyan-50 text-black shadow-sm",idleTab="border-slate-300 bg-white text-black hover:bg-slate-50";
  return <div className="qmes-partners-surround"><div className="space-y-5 qmes-partners-page rounded-xl bg-slate-50 p-5 text-black">
    <style>{`.qmes-partners-surround{margin:-24px;min-height:calc(100vh - 72px);padding:24px;background:linear-gradient(135deg,#d1d5db 0%,#94a3b8 38%,#475569 68%,#172554 100%)}.qmes-partners-page{max-width:100%;box-shadow:0 14px 34px rgba(15,23,42,.22)}.qmes-partners-page,.qmes-partners-page *{box-sizing:border-box}.qmes-partners-page{color:#000!important;overflow:visible}.qmes-partners-page h2,.qmes-partners-page h3,.qmes-partners-page p,.qmes-partners-page th,.qmes-partners-page td,.qmes-partners-page button,.qmes-partners-page input{color:#000}.qmes-partners-page table{table-layout:auto;width:100%;min-width:1050px}.qmes-partners-page th,.qmes-partners-page td{white-space:nowrap;overflow:visible;text-overflow:clip;line-height:1.5;vertical-align:middle}.qmes-partners-page th{padding-top:13px!important;padding-bottom:13px!important}.qmes-partners-page td{padding-top:11px!important;padding-bottom:11px!important}.qmes-partner-register-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:36px;padding:8px 13px;border:1px solid #0891b2;border-radius:7px;background:#0891b2;color:#fff!important;font-size:13px;font-weight:800;line-height:18px;cursor:pointer;white-space:nowrap}.qmes-partner-register-btn *{color:#fff!important}.qmes-partners-page table tbody tr:hover{background:#f8fafc}.qmes-partners-page input{min-height:38px;line-height:20px}@media(max-width:768px){.qmes-partners-surround{margin:-16px;padding:16px;min-height:calc(100vh - 64px)}}`}</style>
    <div><h2 className="text-2xl font-bold">거래처 현황</h2><p className="mt-1 text-sm">고객사와 원료 공급업체를 구분하여 관리합니다.</p></div>
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex shrink-0 gap-2"><button type="button" onClick={()=>switchType("customer")} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${activeType==="customer"?activeTab:idleTab}`}>고객사 목록</button><button type="button" onClick={()=>switchType("supplier")} className={`rounded-lg border px-4 py-2 text-sm font-semibold ${activeType==="supplier"?activeTab:idleTab}`}>공급업체 목록</button></div><div className="min-w-0 flex-1"><input type="search" value={searchText} onChange={e=>setSearchText(e.target.value)} placeholder={activeType==="customer"?"고객사명 또는 고객사 코드 검색":"공급업체명 / 원료명 / LOT 검색"} className={inputClass}/></div></div>
    {saveMessage&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm">{saveMessage}</div>}
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><div className="flex items-center gap-3"><h3 className="font-semibold">{activeType==="customer"?"고객사 목록":"공급업체 목록"}</h3><button type="button" className="qmes-partner-register-btn" data-qmes-partner-register="true"><Plus size={16}/>{activeType==="customer"?"고객사 등록":"공급업체 등록"}</button></div><p className="mt-1 text-xs">{activeType==="customer"?`등록 고객사 ${filteredCustomers.length}건`:`등록 공급업체 ${filteredSuppliers.length}건 · 원료 LOT 작업지시서 연동`}</p></div>{activeType==="supplier"&&<button type="button" onClick={saveSupplierLots} className="rounded-md border border-cyan-400 bg-cyan-50 px-3 py-2 text-xs font-semibold">LOT 저장 · 작업지시서 반영</button>}</div>
    <div className="overflow-x-auto"><table className="text-sm">{activeType==="customer"?<><thead className="bg-slate-100"><tr><th className="px-4">No</th><th className="px-4 text-left">고객사 코드</th><th className="px-4 text-left">고객사명</th><th className="px-4">상태</th><th className="px-4">관리</th></tr></thead><tbody>{filteredCustomers.map((i,x)=><tr key={i.code} className="border-t border-slate-200"><td className="px-4 text-center">{x+1}</td><td className="px-4 font-mono">{i.code}</td><td className="px-4 font-semibold">{i.name}</td><td className="px-4 text-center">{i.status}</td><td className="px-4 text-center"><button type="button" className={btnEdit}>수정</button></td></tr>)}</tbody></>:<><thead className="bg-slate-100"><tr><th className="px-4">No</th><th className="px-4 text-left">공급업체 코드</th><th className="px-4 text-left">공급업체명</th><th className="px-4 text-left">원료명</th><th className="px-4 text-left">최근 원료 LOT No.</th><th className="px-4">상태</th><th className="px-4">관리</th></tr></thead><tbody>{filteredSuppliers.map((i,x)=><tr key={i.code} className="border-t border-slate-200"><td className="px-4 text-center">{x+1}</td><td className="px-4 font-mono">{i.code}</td><td className="px-4 font-semibold">{i.company}</td><td className="px-4">{i.material}</td><td className="px-4"><input value={i.lot} onChange={e=>updateSupplierLot(i.code,e.target.value)} className="w-full min-w-[190px] rounded-md border border-slate-300 bg-white px-3 py-2 font-mono text-black outline-none"/></td><td className="px-4 text-center">{i.status}</td><td className="px-4 text-center"><button type="button" className={btnEdit}>수정</button></td></tr>)}</tbody></>}</table></div></div>
  </div></div>;
}