/* Restored NAMO QMES business extension menus and screens */
function QBEHeader({title,subtitle,action}){return <div className="qbe-title-row"><div><h1 className="qbe-title">{title}</h1><div className="qbe-subtitle">{subtitle}</div></div>{action&&<button type="button" className="qbe-primary">{action}</button>}</div>}
function QBEKpi({label,value,tone=''}){return <div className={`qbe-kpi ${tone}`}><span className="qbe-kpi-label">{label}</span><b className="qbe-kpi-value">{value}</b></div>}
function QBESalesTab(){return <div className="qmes-business-extension"><QBEHeader title="수주 · 납기관리" subtitle="고객 수주와 요청 납기를 생산계획 및 출하계획과 연결합니다." action="+ 신규 수주"/><div className="qbe-kpis"><QBEKpi label="진행 수주" value="0건"/><QBEKpi label="7일 이내 납기" value="0건" tone="orange"/><QBEKpi label="납기 준수율" value="-" tone="green"/><QBEKpi label="지연 위험" value="0건" tone="red"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>수주번호</th><th>고객사</th><th>제품</th><th>수량</th><th>납기일</th><th>생산계획</th><th>출하상태</th></tr></thead><tbody></tbody></table></div></div></div>}
function QBEPlanTab(){return <div className="qmes-business-extension"><QBEHeader title="생산계획 · MRP" subtitle="수주와 현재 적용 Recipe/BOM 기준으로 원료 소요량과 부족량을 계산합니다." action="MRP 재계산"/><div className="qbe-kpis"><QBEKpi label="생산계획" value="0건"/><QBEKpi label="MRP 부족 원료" value="0품목" tone="red"/><QBEKpi label="입고예정" value="0건" tone="orange"/><QBEKpi label="생산 가능" value="-" tone="green"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>생산일</th><th>제품</th><th>계획량</th><th>Recipe</th><th>Revision</th><th>자재상태</th></tr></thead><tbody></tbody></table></div></div></div>}
function QBEPurchaseTab(){return <div className="qmes-business-extension"><QBEHeader title="구매 · 발주관리" subtitle="MRP 부족분을 구매요청 → 발주 → 입고예정 → IQC로 연결합니다." action="+ 발주서 생성"/><div className="qbe-kpis"><QBEKpi label="발주 진행" value="0건"/><QBEKpi label="입고 예정" value="0건" tone="orange"/><QBEKpi label="납기 정상" value="0건" tone="green"/><QBEKpi label="납기 확인" value="0건" tone="red"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>발주번호</th><th>협력사</th><th>원료</th><th>발주량</th><th>요청납기</th><th>입고예정</th><th>IQC 연계</th><th>상태</th></tr></thead><tbody></tbody></table></div></div></div>}
function QBERecipeTab(){return <div className="qmes-business-extension"><QBEHeader title="Recipe / BOM Master" subtitle="제품별 Formula, Revision, 공정조건 및 적용이력을 관리합니다."/></div>}
function QBEShippingTab(){return <div className="qmes-business-extension"><QBEHeader title="출하 · 납품관리" subtitle="OQC 합격 → CoA → 출하계획 → 배송 → 납품완료를 연결합니다." action="+ 출하계획"/><div className="qbe-kpis"><QBEKpi label="출하 예정" value="0건"/><QBEKpi label="OQC 합격" value="0건" tone="green"/><QBEKpi label="CoA 발행대기" value="0건" tone="orange"/><QBEKpi label="납기 위험" value="0건" tone="red"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>출하일</th><th>수주번호</th><th>고객사</th><th>제품</th><th>완제품 LOT</th><th>수량</th><th>OQC</th><th>CoA</th><th>배송</th></tr></thead><tbody></tbody></table></div></div></div>}
window.QBESalesTab=QBESalesTab;window.QBEPlanTab=QBEPlanTab;window.QBEPurchaseTab=QBEPurchaseTab;window.QBERecipeTab=QBERecipeTab;window.QBEShippingTab=QBEShippingTab;
(function(){
 if(window.__QMES_BUSINESS_EXTENSION_RESTORED__)return;window.__QMES_BUSINESS_EXTENSION_RESTORED__=true;
 const menus=[['sales','수주·납기',QBESalesTab],['plan','생산계획·MRP',QBEPlanTab],['purchase','구매·발주',QBEPurchaseTab],['recipe','Recipe/BOM',QBERecipeTab],['shipping','출하·납품',QBEShippingTab]];
 let root=null,host=null;
 function main(){return document.querySelector('#root>div>main')}
 function close(){if(root){try{root.unmount()}catch(e){}root=null}if(host){host.remove();host=null}const m=main();if(m)[...m.children].forEach(c=>{if(c.dataset.qbeHidden==='1'){c.style.removeProperty('display');delete c.dataset.qbeHidden}})}
 function open(id,C,btn){const m=main();if(!m)return;close();host=document.createElement('div');host.id='qmes-business-extension-host';m.prepend(host);[...m.children].forEach(c=>{if(c!==host){c.dataset.qbeHidden='1';c.style.display='none'}});root=ReactDOM.createRoot(host);root.render(<C/>);document.querySelectorAll('.qmes-top-menu-button').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');try{sessionStorage.setItem('qmes_business_extension_tab',id)}catch(e){}window.scrollTo(0,0)}
 function ensure(){const nav=document.querySelector('.qmes-top-menu');if(!nav)return false;menus.forEach(([id,label,C])=>{let item=nav.querySelector(`[data-qbe-menu="${id}"]`);if(!item){item=document.createElement('div');item.className='qmes-top-menu-item';item.dataset.qbeMenu=id;const b=document.createElement('button');b.type='button';b.className='qmes-top-menu-button is-extension';b.textContent=label;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(id,C,b)});item.appendChild(b);nav.appendChild(item)}});return true}
 document.addEventListener('click',e=>{const b=e.target.closest('.qmes-top-menu-button');if(!b||b.classList.contains('is-extension'))return;close();try{sessionStorage.removeItem('qmes_business_extension_tab')}catch(err){}},true);
 function boot(){if(!ensure()){setTimeout(boot,300);return}let saved='';try{saved=sessionStorage.getItem('qmes_business_extension_tab')||''}catch(e){}if(saved){const m=menus.find(x=>x[0]===saved),b=document.querySelector(`[data-qbe-menu="${saved}"] button`);if(m&&b)setTimeout(()=>open(saved,m[2],b),100)}}
 setTimeout(boot,300);
})();