/* NAMO QMES business extension screens - UI first, API integration next. */
function QBEStatus({tone="blue",children}){return <span className={`qbe-status ${tone}`}>{children}</span>}
function QBEKpi({label,value,sub="",tone=""}){return <div className={`qbe-kpi ${tone}`}><span className="qbe-kpi-label">{label}</span><b className="qbe-kpi-value">{value}</b>{sub&&<small className="qbe-kpi-sub">{sub}</small>}</div>}
function QBEHeader({title,subtitle,action,stage="화면 추가"}){return <div className="qbe-title-row"><div><h1 className="qbe-title">{title}<span className="qbe-stage">{stage}</span></h1><div className="qbe-subtitle">{subtitle}</div></div>{action&&<button type="button" className="qbe-primary" onClick={()=>alert("현재는 화면 구성 단계입니다. 다음 단계에서 DB/API 저장 기능을 연결합니다.")}>{action}</button>}</div>}
function QBESalesTab(){return <div className="qmes-business-extension"><QBEHeader title="수주 · 납기관리" subtitle="고객 PO를 생산계획 및 출하계획의 시작점으로 관리합니다." action="+ 신규 수주"/><div className="qbe-kpis"><QBEKpi label="진행 수주" value="8건"/><QBEKpi label="7일 이내 납기" value="3건" tone="orange"/><QBEKpi label="납기 준수율" value="96.8%" tone="green"/><QBEKpi label="지연 위험" value="1건" tone="red"/><QBEKpi label="금월 수주량" value="12.5t" tone="slate"/></div><div className="qbe-card"><div className="qbe-form-grid" style={{marginBottom:14}}><div className="qbe-field"><label>고객사</label><select defaultValue="현대자동차"><option>현대자동차</option><option>삼성SDI</option><option>SK</option></select></div><div className="qbe-field"><label>고객 PO 번호</label><input defaultValue="HM-2026-0824-01"/></div><div className="qbe-field"><label>요청 납기일</label><input type="date" defaultValue="2026-08-30"/></div><div className="qbe-field"><label>제품</label><select><option>전도 슬러리 A</option><option>Binder Solution</option></select></div></div><div className="qbe-table-wrap"><table><thead><tr><th>수주번호</th><th>고객사</th><th>제품</th><th>수량</th><th>납기일</th><th>생산계획</th><th>출하상태</th></tr></thead><tbody><tr><td>SO-260824-01</td><td>현대자동차</td><td>전도 슬러리 A</td><td>3,000 kg</td><td>08/30</td><td><QBEStatus tone="green">반영완료</QBEStatus></td><td><QBEStatus>생산중</QBEStatus></td></tr><tr><td>SO-260823-02</td><td>삼성SDI</td><td>Binder Solution</td><td>2,000 kg</td><td>08/29</td><td><QBEStatus tone="orange">계획대기</QBEStatus></td><td>-</td></tr></tbody></table></div></div></div>}
function QBEPlanTab(){return <div className="qmes-business-extension"><QBEHeader title="생산계획 · MRP" subtitle="수주와 Recipe를 기준으로 원료 필요량, 가용재고 및 부족량을 계산합니다." action="MRP 재계산"/><div className="qbe-grid2"><div className="qbe-card"><h2>생산계획 입력</h2><div className="qbe-form-grid"><div className="qbe-field"><label>생산일</label><input type="date" defaultValue="2026-08-27"/></div><div className="qbe-field"><label>제품</label><select><option>Binder Solution</option></select></div><div className="qbe-field"><label>계획량</label><input defaultValue="2,500 kg"/></div><div className="qbe-field"><label>Recipe Revision</label><select><option>Rev.03</option></select></div></div></div><div className="qbe-card"><h2>계획 판단</h2><div className="qbe-alerts"><div className="qbe-alert blue"><span>현재 생산 가능률</span><b>89.2%</b></div><div className="qbe-alert red"><span>부족 원료</span><b>3 품목</b></div><div className="qbe-alert orange"><span>입고예정 반영 필요</span><b>1건</b></div></div></div></div><div className="qbe-card"><div className="qbe-card-head"><h2>MRP 소요량 계산</h2><span className="qbe-hint">계획 2,500kg · Rev.03</span></div><div className="qbe-table-wrap"><table><thead><tr><th>원료</th><th>배합비</th><th>필요량</th><th>가용재고</th><th>예약재고</th><th>입고예정</th><th>부족량</th><th>조치</th></tr></thead><tbody><tr><td>NMP</td><td>80.0%</td><td>2,000 kg</td><td>1,550</td><td>200</td><td>400</td><td><b style={{color:'#dc2626'}}>250 kg</b></td><td><QBEStatus tone="red">발주 필요</QBEStatus></td></tr><tr><td>PVDF</td><td>5.0%</td><td>125 kg</td><td>80</td><td>0</td><td>50</td><td>0</td><td><QBEStatus tone="green">충족</QBEStatus></td></tr><tr><td>SBR</td><td>6.0%</td><td>150 kg</td><td>210</td><td>20</td><td>0</td><td>0</td><td><QBEStatus tone="green">충족</QBEStatus></td></tr><tr><td>첨가제</td><td>9.0%</td><td>225 kg</td><td>190</td><td>0</td><td>0</td><td><b style={{color:'#dc2626'}}>35 kg</b></td><td><QBEStatus tone="red">발주 필요</QBEStatus></td></tr></tbody></table></div></div></div>}
function QBEPurchaseTab(){return <div className="qmes-business-extension"><QBEHeader title="구매 · 발주관리" subtitle="MRP 부족분을 구매요청 → 발주 → 입고예정 → IQC로 연결합니다." action="+ 발주서 생성"/><div className="qbe-kpis"><QBEKpi label="발주 진행" value="5건"/><QBEKpi label="입고 예정" value="3건" tone="orange"/><QBEKpi label="납기 정상" value="4건" tone="green"/><QBEKpi label="납기 확인" value="1건" tone="red"/><QBEKpi label="금월 발주" value="4.8t" tone="slate"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>발주번호</th><th>협력사</th><th>원료</th><th>발주량</th><th>요청납기</th><th>입고예정</th><th>IQC 연계</th><th>상태</th></tr></thead><tbody><tr><td>PO-260824-01</td><td>Supplier A</td><td>NMP</td><td>500 kg</td><td>08/26</td><td>08/25</td><td>예정</td><td><QBEStatus>출하완료</QBEStatus></td></tr><tr><td>PO-260824-02</td><td>Supplier B</td><td>첨가제</td><td>100 kg</td><td>08/27</td><td>-</td><td>-</td><td><QBEStatus tone="orange">납기확인</QBEStatus></td></tr></tbody></table></div></div></div>}
function QBERecipeTab(){return <div className="qmes-business-extension"><QBEHeader title="Recipe / BOM Master" subtitle="제품별 표준 배합비, 표준투입량, Revision, 적용일 및 승인이력을 관리합니다." action="+ 신규 Revision"/><div className="qbe-split"><div className="qbe-card"><h2>제품 Recipe</h2><div className="qbe-box"><h3>Binder Solution · Rev.03</h3><div className="qbe-note">적용일: <b>2026-08-20</b><br/>고객사: 현대자동차 / 공용<br/>기준 생산량: <b>1,000 kg</b><br/>상태: <QBEStatus tone="green">승인</QBEStatus></div></div><div className="qbe-box"><h3>개정 이력</h3><div className="qbe-note">Rev.03 — NMP 79% → 80%<br/>Rev.02 — 첨가제 B 추가<br/>Rev.01 — 최초 등록</div></div></div><div className="qbe-card"><h2>표준 배합표</h2><div className="qbe-table-wrap"><table><thead><tr><th>No</th><th>원료</th><th>배합비</th><th>1,000kg 기준</th><th>투입순서</th><th>CTQ</th></tr></thead><tbody><tr><td>1</td><td>NMP</td><td>80.0%</td><td>800 kg</td><td>1</td><td>-</td></tr><tr><td>2</td><td>PVDF</td><td>5.0%</td><td>50 kg</td><td>2</td><td>점도</td></tr><tr><td>3</td><td>SBR</td><td>6.0%</td><td>60 kg</td><td>3</td><td>고형분</td></tr><tr><td>4</td><td>첨가제</td><td>9.0%</td><td>90 kg</td><td>4</td><td>Dmax</td></tr></tbody></table></div></div></div></div>}
function QBEShippingTab(){return <div className="qmes-business-extension"><QBEHeader title="출하 · 납품관리" subtitle="OQC 합격 → CoA 발행 → 출하계획 → 배송 → 고객 납품완료를 연결합니다." action="+ 출하계획"/><div className="qbe-kpis"><QBEKpi label="출하 예정" value="4건"/><QBEKpi label="OQC 합격" value="3건" tone="green"/><QBEKpi label="CoA 발행대기" value="1건" tone="orange"/><QBEKpi label="출하가능 재고" value="5.8t" tone="slate"/><QBEKpi label="납기 위험" value="0건" tone="red"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>출하일</th><th>수주번호</th><th>고객사</th><th>제품</th><th>완제품 LOT</th><th>수량</th><th>OQC</th><th>CoA</th><th>배송</th></tr></thead><tbody><tr><td>08/26</td><td>SO-260824-01</td><td>현대자동차</td><td>전도 슬러리 A</td><td>FG-240824-01</td><td>2,000 kg</td><td><QBEStatus tone="green">합격</QBEStatus></td><td><QBEStatus tone="green">발행</QBEStatus></td><td><QBEStatus>배차완료</QBEStatus></td></tr><tr><td>08/27</td><td>SO-260823-02</td><td>삼성SDI</td><td>Binder Solution</td><td>FG-250825-01</td><td>1,500 kg</td><td><QBEStatus tone="orange">검사대기</QBEStatus></td><td>-</td><td>-</td></tr></tbody></table></div></div></div>}
window.QBESalesTab=QBESalesTab;window.QBEPlanTab=QBEPlanTab;window.QBEPurchaseTab=QBEPurchaseTab;window.QBERecipeTab=QBERecipeTab;window.QBEShippingTab=QBEShippingTab;

(function installQmesBusinessExtension(){
  if(window.__QMES_BUSINESS_EXTENSION_INSTALLED__)return;window.__QMES_BUSINESS_EXTENSION_INSTALLED__=true;
  const menus=[['sales','수주·납기',QBESalesTab],['plan','생산계획·MRP',QBEPlanTab],['purchase','구매·발주',QBEPurchaseTab],['recipe','Recipe/BOM',QBERecipeTab],['shipping','출하·납품',QBEShippingTab]];
  let extensionRoot=null,host=null;
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
  function closeExtension(){if(extensionRoot){try{extensionRoot.unmount()}catch(e){}extensionRoot=null}if(host){host.remove();host=null}document.querySelectorAll('.qmes-top-menu-button.is-extension').forEach(b=>b.classList.remove('is-active'));}
  function openExtension(id,Component,button){const main=document.querySelector('#root>div>main');if(!main)return;closeExtension();host=document.createElement('div');host.id='qmes-business-extension-host';host.style.width='100%';main.prepend(host);Array.from(main.children).forEach(child=>{if(child!==host){child.dataset.qbeHidden='1';child.style.display='none'}});extensionRoot=ReactDOM.createRoot(host);extensionRoot.render(<Component/>);document.querySelectorAll('.qmes-top-menu-button').forEach(b=>b.classList.remove('is-active'));button?.classList.add('is-active');try{sessionStorage.setItem('qmes_business_extension_tab',id)}catch(e){}window.scrollTo({top:0,behavior:'smooth'});}
  function restoreNative(){closeExtension();const main=document.querySelector('#root>div>main');if(main)Array.from(main.children).forEach(child=>{if(child.dataset.qbeHidden==='1'){child.style.removeProperty('display');delete child.dataset.qbeHidden}});try{sessionStorage.removeItem('qmes_business_extension_tab')}catch(e){}}
  function ensureButtons(){const nav=document.querySelector('.qmes-top-menu');if(!nav)return false;menus.forEach(([id,label,Component])=>{let item=nav.querySelector(`[data-qbe-menu="${id}"]`);if(item)return;item=document.createElement('div');item.className='qmes-top-menu-item';item.dataset.qbeMenu=id;const b=document.createElement('button');b.type='button';b.className='qmes-top-menu-button is-extension';b.innerHTML=`<span>${label}</span><i class="qmes-extension-badge">추가</i>`;b.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();openExtension(id,Component,b)});item.appendChild(b);nav.appendChild(item)});return true;}
  document.addEventListener('click',event=>{const b=event.target.closest?.('.qmes-top-menu-button');if(b&&!b.classList.contains('is-extension'))restoreNative()},true);
  const observer=new MutationObserver(()=>ensureButtons());
  function start(){ensureButtons();observer.observe(document.documentElement,{childList:true,subtree:true});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.qmesCloseBusinessExtension=restoreNative;
})();
