/* NAMO QMES business extension screens */
function QBEStatus({tone="blue",children}){return <span className={`qbe-status ${tone}`}>{children}</span>}
function QBEKpi({label,value,sub="",tone=""}){return <div className={`qbe-kpi ${tone}`}><span className="qbe-kpi-label">{label}</span><b className="qbe-kpi-value">{value}</b>{sub&&<small className="qbe-kpi-sub">{sub}</small>}</div>}
function QBEHeader({title,subtitle,action}){return <div className="qbe-title-row"><div><h1 className="qbe-title">{title}</h1><div className="qbe-subtitle">{subtitle}</div></div>{action&&<button type="button" className="qbe-primary">{action}</button>}</div>}
function QBESalesTab(){return <div className="qmes-business-extension"><QBEHeader title="수주 · 납기관리" subtitle="고객 PO를 생산계획 및 출하계획의 시작점으로 관리합니다." action="+ 신규 수주"/><div className="qbe-kpis"><QBEKpi label="진행 수주" value="0건"/><QBEKpi label="7일 이내 납기" value="0건" tone="orange"/><QBEKpi label="납기 준수율" value="-" tone="green"/><QBEKpi label="지연 위험" value="0건" tone="red"/><QBEKpi label="금월 수주량" value="0" tone="slate"/></div><div className="qbe-card"><div className="qbe-form-grid" style={{marginBottom:14}}><div className="qbe-field"><label>고객사</label><select defaultValue=""><option value="">선택</option></select></div><div className="qbe-field"><label>고객 PO 번호</label><input defaultValue=""/></div><div className="qbe-field"><label>요청 납기일</label><input type="date" defaultValue=""/></div><div className="qbe-field"><label>제품</label><select defaultValue=""><option value="">선택</option></select></div></div><div className="qbe-table-wrap"><table><thead><tr><th>수주번호</th><th>고객사</th><th>제품</th><th>수량</th><th>납기일</th><th>생산계획</th><th>출하상태</th></tr></thead><tbody></tbody></table></div></div></div>}
function QBEPlanTab(){return <div className="qmes-business-extension"><QBEHeader title="생산계획 · MRP" subtitle="수주와 Recipe를 기준으로 원료 필요량, 가용재고 및 부족량을 계산합니다." action="MRP 재계산"/><div className="qbe-grid2"><div className="qbe-card"><h2>생산계획 입력</h2><div className="qbe-form-grid"><div className="qbe-field"><label>생산일</label><input type="date" defaultValue=""/></div><div className="qbe-field"><label>제품</label><select defaultValue=""><option value="">선택</option></select></div><div className="qbe-field"><label>계획량</label><input defaultValue=""/></div><div className="qbe-field"><label>Recipe Revision</label><select defaultValue=""><option value="">선택</option></select></div></div></div><div className="qbe-card"><h2>계획 판단</h2><div className="qbe-alerts"><div className="qbe-alert blue"><span>현재 생산 가능률</span><b>-</b></div><div className="qbe-alert red"><span>부족 원료</span><b>0 품목</b></div><div className="qbe-alert orange"><span>입고예정 반영 필요</span><b>0건</b></div></div></div></div><div className="qbe-card"><div className="qbe-card-head"><h2>MRP 소요량 계산</h2><span className="qbe-hint"></span></div><div className="qbe-table-wrap"><table><thead><tr><th>원료</th><th>배합비</th><th>필요량</th><th>가용재고</th><th>예약재고</th><th>입고예정</th><th>부족량</th><th>조치</th></tr></thead><tbody></tbody></table></div></div></div>}
function QBEPurchaseTab(){return <div className="qmes-business-extension"><QBEHeader title="구매 · 발주관리" subtitle="MRP 부족분을 구매요청 → 발주 → 입고예정 → IQC로 연결합니다." action="+ 발주서 생성"/><div className="qbe-kpis"><QBEKpi label="발주 진행" value="0건"/><QBEKpi label="입고 예정" value="0건" tone="orange"/><QBEKpi label="납기 정상" value="0건" tone="green"/><QBEKpi label="납기 확인" value="0건" tone="red"/><QBEKpi label="금월 발주" value="0" tone="slate"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>발주번호</th><th>협력사</th><th>원료</th><th>발주량</th><th>요청납기</th><th>입고예정</th><th>IQC 연계</th><th>상태</th></tr></thead><tbody></tbody></table></div></div></div>}
function QBERecipeTab(){return <div className="qmes-business-extension"><QBEHeader title="Recipe / BOM Master" subtitle="제품별 표준 배합비, 표준투입량, Revision, 적용일 및 승인이력을 관리합니다." action="+ 신규 Revision"/><div className="qbe-split"><div className="qbe-card"><h2>제품 Recipe</h2><div className="qbe-box"><h3>등록된 Recipe 없음</h3><div className="qbe-note">신규 Revision을 등록하면 이곳에 표시됩니다.</div></div><div className="qbe-box"><h3>개정 이력</h3><div className="qbe-note">등록된 이력이 없습니다.</div></div></div><div className="qbe-card"><h2>표준 배합표</h2><div className="qbe-table-wrap"><table><thead><tr><th>No</th><th>원료</th><th>배합비</th><th>기준 투입량</th><th>투입순서</th><th>CTQ</th></tr></thead><tbody></tbody></table></div></div></div></div>}
function QBEShippingTab(){return <div className="qmes-business-extension"><QBEHeader title="출하 · 납품관리" subtitle="OQC 합격 → CoA 발행 → 출하계획 → 배송 → 고객 납품완료를 연결합니다." action="+ 출하계획"/><div className="qbe-kpis"><QBEKpi label="출하 예정" value="0건"/><QBEKpi label="OQC 합격" value="0건" tone="green"/><QBEKpi label="CoA 발행대기" value="0건" tone="orange"/><QBEKpi label="출하가능 재고" value="0" tone="slate"/><QBEKpi label="납기 위험" value="0건" tone="red"/></div><div className="qbe-card"><div className="qbe-table-wrap"><table><thead><tr><th>출하일</th><th>수주번호</th><th>고객사</th><th>제품</th><th>완제품 LOT</th><th>수량</th><th>OQC</th><th>CoA</th><th>배송</th></tr></thead><tbody></tbody></table></div></div></div>}
window.QBESalesTab=QBESalesTab;window.QBEPlanTab=QBEPlanTab;window.QBEPurchaseTab=QBEPurchaseTab;window.QBERecipeTab=QBERecipeTab;window.QBEShippingTab=QBEShippingTab;

(function installQmesBusinessExtension(){
  if(window.__QMES_BUSINESS_EXTENSION_INSTALLED__)return;window.__QMES_BUSINESS_EXTENSION_INSTALLED__=true;
  const menus=[['sales','수주·납기',QBESalesTab],['plan','생산계획·MRP',QBEPlanTab],['purchase','구매·발주',QBEPurchaseTab],['recipe','Recipe/BOM',QBERecipeTab],['shipping','출하·납품',QBEShippingTab]];
  let extensionRoot=null,host=null,dashHost=null;
  function mainEl(){return document.querySelector('#root>div>main')}
  function closeDash(){if(dashHost){dashHost.remove();dashHost=null}const main=mainEl();if(main)Array.from(main.children).forEach(child=>{if(child.dataset.qpdHidden==='1'){child.style.removeProperty('display');delete child.dataset.qpdHidden}})}
  function closeExtension(){if(extensionRoot){try{extensionRoot.unmount()}catch(e){}extensionRoot=null}if(host){host.remove();host=null}document.querySelectorAll('.qmes-top-menu-button.is-extension').forEach(b=>b.classList.remove('is-active'));}
  function openExtension(id,Component,button){const main=mainEl();if(!main)return;closeDash();closeExtension();host=document.createElement('div');host.id='qmes-business-extension-host';host.style.width='100%';main.prepend(host);Array.from(main.children).forEach(child=>{if(child!==host){child.dataset.qbeHidden='1';child.style.display='none'}});extensionRoot=ReactDOM.createRoot(host);extensionRoot.render(<Component/>);document.querySelectorAll('.qmes-top-menu-button').forEach(b=>b.classList.remove('is-active'));button?.classList.add('is-active');try{sessionStorage.setItem('qmes_business_extension_tab',id)}catch(e){}syncSideActive(id);window.scrollTo({top:0,behavior:'smooth'});}
  function restoreNative(){closeExtension();const main=mainEl();if(main)Array.from(main.children).forEach(child=>{if(child.dataset.qbeHidden==='1'){child.style.removeProperty('display');delete child.dataset.qbeHidden}});try{sessionStorage.removeItem('qmes_business_extension_tab')}catch(e){}setTimeout(syncDashboard,30)}
  function ensureButtons(){const nav=document.querySelector('.qmes-top-menu');if(!nav)return false;menus.forEach(([id,label,Component])=>{let item=nav.querySelector(`[data-qbe-menu="${id}"]`);if(item){const old=item.querySelector('.qmes-extension-badge');if(old)old.remove();return}item=document.createElement('div');item.className='qmes-top-menu-item';item.dataset.qbeMenu=id;const b=document.createElement('button');b.type='button';b.className='qmes-top-menu-button is-extension';b.innerHTML=`<span>${label}</span>`;b.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();openExtension(id,Component,b)});item.appendChild(b);nav.appendChild(item)});return true;}
  function clickTop(label){const buttons=[...document.querySelectorAll('.qmes-top-menu-button')];const b=buttons.find(x=>x.textContent.replace(/추가/g,'').trim().startsWith(label));if(b)b.click()}
  function sidebarHtml(){return `<div class="qps-search"><input placeholder="메뉴 검색"></div><div class="qps-group">현재 QMES</div>${[['dash','▦','종합 대시보드'],['productionMenu','P','생산관리'],['qualityMenu','Q','품질검사'],['pop','iP','현장입력'],['inv','I','재고관리'],['partners','C','거래처 현황'],['eq','E','설비관리'],['trace','L','LOT 추적'],['nonconformityMenu','8D','부적합관리']].map(x=>`<button class="qps-side-btn" data-qps="${x[0]}"><span class="qps-ico">${x[1]}</span>${x[2]}<span class="qps-mini now">현재</span></button>`).join('')}<div class="qps-group">업무 관리</div>${[['sales','SO','수주 · 납기관리'],['plan','MRP','생산계획 · MRP'],['purchase','PO','구매 · 발주관리'],['recipe','R','Recipe / BOM'],['shipping','S','출하 · 납품관리']].map(x=>`<button class="qps-side-btn" data-qps="${x[0]}"><span class="qps-ico">${x[1]}</span>${x[2]}</button>`).join('')}`}
  function ensureShell(){const root=document.querySelector('#root>div');const header=root?.querySelector(':scope>header');const main=mainEl();if(!root||!header||!main)return false;root.classList.add('qmes-preview-shell');header.firstElementChild?.classList.add('qps-header-main');header.querySelector('img[alt="NAMO Chemical"]')?.parentElement?.classList.add('qps-brand');const account=header.querySelector('button[aria-label="계정 설정 열기"]');if(account){account.classList.add('qps-user');account.firstElementChild?.classList.add('qps-avatar')}header.querySelector('button[aria-label^="NAMO Talk 닫기"],button[aria-label^="NAMO Talk 열기"]')?.classList.add('qps-talk');main.classList.add('qps-content');main.style.marginLeft=window.innerWidth>900?'220px':'0';main.style.width=window.innerWidth>900?'calc(100% - 220px)':'100%';let side=root.querySelector('#qps-sidebar');if(!side){side=document.createElement('aside');side.id='qps-sidebar';side.className='qps-sidebar';side.innerHTML=sidebarHtml();side.style.position='fixed';side.style.left='0';side.style.top='114px';side.style.bottom='0';side.style.overflowY='auto';side.style.zIndex='20';root.appendChild(side);side.addEventListener('click',e=>{const b=e.target.closest('[data-qps]');if(!b)return;const id=b.dataset.qps;if(['sales','plan','purchase','recipe','shipping'].includes(id)){document.querySelector(`[data-qbe-menu="${id}"] button`)?.click();return}const labels={dash:'대시보드',productionMenu:'생산관리',qualityMenu:'품질검사',pop:'현장입력',inv:'재고관리',partners:'거래처 현황',eq:'설비관리',trace:'LOT 추적',nonconformityMenu:'부적합관리'};clickTop(labels[id])});side.querySelector('input')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();side.querySelectorAll('.qps-side-btn').forEach(b=>b.style.display=!q||b.textContent.toLowerCase().includes(q)?'flex':'none')})}else{const addGroup=[...side.querySelectorAll('.qps-group')].find(el=>el.textContent.includes('추가 권장'));if(addGroup)addGroup.textContent='업무 관리';side.querySelectorAll('.qps-mini.add').forEach(el=>el.remove())}return true}
  function dashboardHtml(){return `<div class="qmes-preview-dashboard"><div class="qpd-title-row"><div><h1>종합 대시보드</h1><p>기존 QMES에 수주·MRP·구매·Recipe·납품 흐름을 합친 통합 화면</p></div><button class="qpd-primary" data-qpd-ext="plan">+ 생산계획 등록</button></div><div class="qpd-kpis"><div class="qpd-kpi"><span>금월 수주</span><b>12,500 kg</b><small>5건 / 고객사 3개</small></div><div class="qpd-kpi orange"><span>생산 예정</span><b>8,400 kg</b><small>금주 작업지시 6건</small></div><div class="qpd-kpi red"><span>MRP 부족 원료</span><b>3 품목</b><small>NMP · PVDF · 첨가제</small></div><div class="qpd-kpi green"><span>생산 완료율</span><b>92.4%</b><small>계획 대비 실적</small></div><div class="qpd-kpi slate"><span>출하 대기</span><b>2,150 kg</b><small>OQC 합격 기준</small></div></div><section class="qpd-card"><div class="qpd-card-head"><h2>QMES 통합 업무 흐름</h2><span>파랑 = 기존 / 주황 = 업무</span></div><div class="qpd-flow">${[['add','수주','고객 PO / 납기','sales'],['add','생산계획','월·주·일 계획','plan'],['add','MRP','Recipe 소요량','plan'],['add','구매/발주','부족원료 확보','purchase'],['now','IQC','수입검사','qualityMenu'],['now','원재료 재고','RM / 위치 / LOT','inv'],['now','작업지시','생산 LOT','productionMenu'],['now','생산공정','계량/배합/충진','productionMenu'],['now','PQC','공정검사','qualityMenu'],['now','OQC / CoA','출하검사','qualityMenu'],['add','출하/납품','납품완료','shipping']].map((x,i)=>`<button class="qpd-flow-step ${x[0]}" data-qpd-go="${x[3]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>${i<10?'<i>›</i>':''}`).join('')}</div></section><div class="qpd-grid2"><section class="qpd-card"><div class="qpd-card-head"><h2>금주 생산계획 / 진행현황</h2><button data-qpd-ext="plan">전체보기</button></div><div class="qpd-table-wrap"><table><thead><tr><th>생산일</th><th>고객사</th><th>제품명</th><th>생산 LOT</th><th>계획량</th><th>진행상태</th></tr></thead><tbody><tr><td>08-24</td><td>현대자동차</td><td>전도 슬러리 A</td><td>240824-01</td><td>2,000 kg</td><td><span class="qpd-status blue">PQC 진행</span></td></tr><tr><td>08-25</td><td>삼성SDI</td><td>Binder Solution</td><td>250825-01</td><td>1,500 kg</td><td><span class="qpd-status orange">원료 준비</span></td></tr><tr><td>08-26</td><td>SK</td><td>전도 슬러리 B</td><td>260826-01</td><td>2,400 kg</td><td><span class="qpd-status green">자재 확보</span></td></tr><tr><td>08-27</td><td>현대자동차</td><td>Binder Solution</td><td>270827-01</td><td>2,500 kg</td><td><span class="qpd-status red">NMP 부족</span></td></tr></tbody></table></div></section><section class="qpd-card"><div class="qpd-card-head"><h2>실행 필요 알림</h2><span>4건</span></div><div class="qpd-alerts"><div class="red"><span>NMP 재고 250kg 부족</span><b>발주 필요</b></div><div class="orange"><span>PVDF 입고예정일 임박</span><b>08/25</b></div><div class="blue"><span>LOT 240824-01 PQC 대기</span><b>검사실</b></div><div class="orange"><span>현대자동차 출하 예정</span><b>08/26</b></div></div></section></div></div>`}
  function syncSideActive(id){document.querySelectorAll('.qps-side-btn').forEach(b=>b.classList.toggle('active',b.dataset.qps===id))}
  function syncDashboard(){if(host)return;const main=mainEl();if(!main)return;const tab=(()=>{try{return sessionStorage.getItem('qmes_current_tab')||'dash'}catch(e){return'dash'}})();syncSideActive(tab);if(tab!=='dash'){closeDash();return}if(dashHost)return;dashHost=document.createElement('div');dashHost.id='qmes-preview-dashboard-host';dashHost.innerHTML=dashboardHtml();main.prepend(dashHost);Array.from(main.children).forEach(child=>{if(child!==dashHost){child.dataset.qpdHidden='1';child.style.display='none'}});dashHost.addEventListener('click',e=>{const ext=e.target.closest('[data-qpd-ext]');if(ext){document.querySelector(`[data-qbe-menu="${ext.dataset.qpdExt}"] button`)?.click();return}const go=e.target.closest('[data-qpd-go]');if(!go)return;const id=go.dataset.qpdGo;if(['sales','plan','purchase','recipe','shipping'].includes(id))document.querySelector(`[data-qbe-menu="${id}"] button`)?.click();else clickTop({qualityMenu:'품질검사',productionMenu:'생산관리',inv:'재고관리'}[id]||id)})}
  document.addEventListener('click',event=>{const b=event.target.closest?.('.qmes-top-menu-button');if(b&&!b.classList.contains('is-extension')){restoreNative();setTimeout(syncDashboard,80)}},true);
  const observer=new MutationObserver(()=>{ensureButtons();ensureShell()});
  function start(){ensureButtons();ensureShell();syncDashboard();observer.observe(document.documentElement,{childList:true,subtree:true});setInterval(()=>{ensureButtons();ensureShell();syncDashboard()},500);window.addEventListener('resize',()=>{const main=mainEl();if(main){main.style.marginLeft=window.innerWidth>900?'220px':'0';main.style.width=window.innerWidth>900?'calc(100% - 220px)':'100%'}const side=document.querySelector('#qps-sidebar');if(side)side.style.display=window.innerWidth>900?'block':'none'})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.qmesCloseBusinessExtension=restoreNative;
})();